import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div class = "container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="m-20 flex place-content-center space-x-4 bg-slate-100 p-5">
          <div>Home</div>
          <div>About Us</div>
          <div>Services</div>
          <div>Treatment</div>
          </div>
          <h1 className="text-5xl text-[#1E3888] font-bold m-11 text-center letter-spacing: -0.05em">
        Transform your school into a holistic development place.
        </h1>

      <h3 class="text-blue-900 text-center">Heal100 is an Initiative that cater to the allround development of young children </h3>
      <h3 class="text-blue-900 text-center">and address their mental wellness needs.</h3>

          <div class="m-20 flex place-content-center space-x-4">
          <div>Counseling</div>
          <div>Therapy</div>
          <div>Wellness</div>
  <div>Lifeskill</div>
</div>
    
<div class = "flex place-content-center">
  <button class = "bg-blue-900 text-white text-sm rounded-3xl p-3">Connect with us</button>
  </div>
    </div>
  )
}
