import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

    function onClickHandler() {
        alert("clicked");
    }
  return (
    <div class = "container m-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <div class="m-20 flex place-content-center space-x-4 bg-slate-100 p-5 shadow-lg rounded-md">
          <div>Home</div>
          <div>About Us</div>
          <div>Services</div>
          <div>Treatment</div>
          </div>
          <h1 className="text-5xl text-[#1E3888] font-bold m-11 text-center letter-spacing: -0.05em">
        Transform your school into a holistic development place
        </h1>

      <h3 class="text-slate-900 text-center">Heal100 is an Initiative that cater to the allround development of young children </h3>
      <h3 class="text-slate-900 text-center">and address their mental wellness needs</h3>

          <div class="m-10 flex place-content-center space-x-4 text-xl font-bold text-[#1E3888]">
          <div>Counseling</div>
          <div>Therapy</div>
          <div>Wellness</div>
  <div>Lifeskill</div>
</div>
    
<div class = "flex place-content-center">
  <button class = "bg-blue-900 text-white text-sm rounded-3xl p-4 shadow-lg shadow-slate-500" onClick={onClickHandler}>Connect with us</button>
  </div>
    </div>
  )
}
